<?php
// ============================================================
// login.php - Login Page: Phone Number Entry + OTP Generation
// OTP is simulated (shown on screen, no SMS sent)
// ============================================================
session_start();

// If already logged in, go to vote page
if (isset($_SESSION['user_id'])) {
    header("Location: vote.php");
    exit();
}

// Handle phone number submission and store in session
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['phone'])) {
    $phone = trim($_POST['phone']);

    // Basic validation: must be 10 digits
    if (!preg_match('/^[0-9]{10}$/', $phone)) {
        $error = "Please enter a valid 10-digit phone number.";
    } else {
        // Store phone and OTP in session for verification
        $_SESSION['login_phone'] = $phone;
        $_SESSION['otp_generated'] = $_POST['otp_generated']; // OTP generated by JS
        header("Location: verify.php");
        exit();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login – VoteNow 2025</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>

<div class="card">
    <!-- Logo and Title -->
    <div style="text-align:center; margin-bottom:20px;">
        <div style="font-size:42px;">🗳️</div>
        <div class="card-title">VoteNow 2025</div>
        <div class="card-subtitle">Enter your phone number to receive OTP</div>
    </div>

    <!-- Error Message -->
    <?php if (isset($error)): ?>
        <div class="alert alert-error"><?php echo htmlspecialchars($error); ?></div>
    <?php endif; ?>

    <!-- Login Form -->
    <form method="POST" action="login.php">

        <!-- Phone Number -->
        <div class="form-group">
            <label for="phone">📱 Phone Number</label>
            <input
                type="text"
                id="phone"
                name="phone"
                placeholder="Enter 10-digit mobile number"
                maxlength="10"
                oninput="validatePhone(this)"
                required
                value="<?php echo isset($_SESSION['login_phone']) ? htmlspecialchars($_SESSION['login_phone']) : ''; ?>"
            >
        </div>

        <!-- Generate OTP Button -->
        <button type="button" id="generate-btn" class="btn btn-primary"
            style="margin-bottom:16px; background:#f9ab00; color:#333;"
            onclick="generateOTP()">
            Generate OTP
        </button>

        <!-- OTP Display Box (hidden until OTP is generated) -->
        <div id="otp-box" class="otp-display" style="display:none;">
            <p>🔐 Your OTP (for simulation):</p>
            <div class="otp-code" id="otp_display_code">------</div>
            <p style="margin-top:6px; font-size:12px; color:#999;">In a real system, this would be sent via SMS.</p>
        </div>

        <!-- Hidden field to carry OTP to server -->
        <input type="hidden" id="otp_generated" name="otp_generated" value="">

        <!-- OTP Verify Section (hidden until OTP is generated) -->
        <div id="verify-section" style="display:none;">
            <div class="alert alert-info">OTP generated! Click "Continue to Verify" to proceed.</div>
            <button type="submit" class="btn btn-primary">Continue to Verify →</button>
        </div>

    </form>

    <p style="text-align:center; margin-top:18px; font-size:13px; color:#aaa;">
        College Election 2025 | Secure & Fair Voting
    </p>
</div>

<script src="script.js"></script>
</body>
</html>
